### ISSUE TITLE
Change scaffolding for better understanding

### ISSUE THREAD

**Issue by not-so-cool-anymore** [Ragnarok-framework/ragnarok_server#1]
You can change the scaffolding of the repo in order to make it better to understand. Some notes are:

- add main.py to the source directory;
- move the packet_maker.py and port_finder.py to a modules/ directory inside the source directory of the project.

**Comment by LuboNenov** [comment]
Hello,
Thank you for the feedback. Everything is now up and running. We have made some new adjustments and optimizations for the client and server scaffolding.
Hope you enjoy our framework!
Ragnarok Dev Team
